#!/usr/bin/env bash
options="-f --help --float "
tools=" one "
one_opt="-i --int "


hasword() {
	word=$1
	shift
	args="$@"
	for w in $args; do
		if [ "$word" = "$w" ]; then
			echo 1
			return 0
		fi
	done

	echo 0
}

complete_files() {
	_compopt_o_filenames
	COMPREPLY+=( $( compgen -f -- "$cur" ) $( compgen -d -- "$cur" ) )
}

_rep() {
	COMPREPLY=()
	local cur prev
	_get_comp_words_by_ref cur prev

	if [ ${COMP_CWORD} -eq 1 ]; then
		if [[ ${cur} == -* ]]; then
			COMPREPLY=( $(compgen -W "${options}" -- $cur) )
			return 0
		fi

		if [[ ${tools} == "" ]]; then
			complete_files
			return 0
		fi

		COMPREPLY=( $(compgen -W "${tools}" -- $cur) )
		return 0
	fi

	if [[ ${cur} == -* ]]; then
		case ${prev} in
			"one")
				COMPREPLY=( $(compgen -W "${one_opt}" -- $cur) )
				return 0
				;;
			*)
				if [ $(hasword ${prev} ${one_opt}) == "1" ]; then
					COMPREPLY=( $(compgen -W "${one_opt}" -- $cur) )
					return 0
				fi

				if [[ $(hasword ${prev} ${options}) == "1" ]]; then
					COMPREPLY=( $(compgen -W "${options}" -- $cur) )
					return 0
				fi
				;;
		esac
	fi

	if [[ $(hasword ${prev} ${options}) == "1" ]]; then
		if [[ ${tools} == "" ]]; then
			complete_files
			return 0
		fi

		COMPREPLY=( $(compgen -W "${tools}" -- $cur) )
		return 0
	fi

	complete_files
	return 0
}

complete -F _rep rep

